travis:
  secure:
    BINSTAR_TOKEN: NMh/Eh14mkfCkRtlEotzP9XTp7YCsC3uw42puu6gB67yi+WaiR1v3dRPtYf3EEmi+EKeIncPfFtRd7/sql1bDEWHiAApE+lg34wltF/QTpcbxTkfGl6xxWWypPwesu3G+mz8xlN9VQVowBxtUu5S+8vEGZXe9sypQBdONzAS8PFVThjM8YCf97JkP6J6IavCZDMoeDZG+S3qVjFNOJZPf+TmjYkRw8DVK26DY+qH5FnJc9IQpUEjMbyYXa5k6ZYmp4Ck1yqTcCv49ECCKxDu9shyWZbFMKTtlZu9TkBdCHP1a3VKvgNCeDTTARwnynkPmuuyzk5cHV+Ui4mZSDp39wNiHAXernFyK9FgbaOmP5zJG67MwbXs1qwHlawDijcWJmDqT2CIlcxm662ohGFM43Ii7UrqrekZwJzCCNxGaWBGSHaEtPM+P67GDyt1Z6S+OvdSFfDzMyyDv26jK1gnAsmxyel59BVbQ210gWovKgyqQQ/7/P7wgXflQMai+zBkoqJ/Gmo/PhaPKsjy7DvTFQpgKDtebxQs0KhIvIzRaLs/OLWr31p8u46vjizM5QZET6sSeLbuQhq1XVFLHjCpbSHW5PfRkdfJzaaVebHE+/uuMkgi+hKUZaV0Mk0Vlve5G+pVxIdeG2xx0xmqwpPaWzOPa9vSk/WXpycP5lWGavU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
